# Generated by Django 6.0.2 on 2026-02-28 09:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denomination',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='denomination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denomination',
            name='name',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchase_product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_product',
            name='product',
            field=models.ForeignKey(db_column='product_id', default='', on_delete=django.db.models.deletion.CASCADE, to='purchase.product', to_field='product_token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_product',
            name='purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='denomination',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchase_product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
